vm_spec = {
  name: "bbf-kubernetes",
  box: "generic/ubuntu2204",
  cpu: 4,
  mem: 16384,
  private_ip: "192.168.3.101",
}

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"
  config.ssh.forward_agent = true

  config.vm.define vm_spec[:name] do |host|
    host.vm.hostname = vm_spec[:name]
    host.vm.box = vm_spec[:box]
    host.vm.network :private_network, ip: vm_spec[:private_ip]
    host.vm.provider "virtualbox" do |vbox|
      vbox.gui = false
      vbox.cpus = vm_spec[:cpu]
      vbox.memory = vm_spec[:mem]
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Install the Docker
    apt-get update
    apt-get install -y ca-certificates curl
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    usermod -aG docker vagrant

    # Install the Golang
    snap install go --classic
  SHELL
end
